### ISSUE TITLE
Question - keypad 

### ISSUE THREAD

**Issue by craigwitter** [hwstar/8-zone-sensor-panel#1]
Good work! Will this work with a honeywell keypad?

Thanks,
Craig

**Comment by hwstar** [comment]
Not directly. This is something I might provide with an external board. There's a connector with RXD and TXD at 12 volt levels, but it is not electrically compatible with the honeywell keypad, and due to the precise timing constraints of the signalling the keypad requires this is best done by a dedicated external processor. I have done some experiments on the bench with 6139 keypads and and I have a 6160 coming.

**Comment by hwstar** [comment]
A keypad adapter board is in the works. I have a prototype working with 2 Honeywell keypads 6139 and 6160.
![20231021_122247](https://github.com/hwstar/8-zone-sensor-panel/assets/1753715/89163c4d-f1b5-4177-b5c9-8023ea932991)
